### ISSUE TITLE
Please add dual-license statement for Apache Public License 2.0 to perl files, LICENSE, README

### ISSUE THREAD

**Issue by cranderson** [Leont/crypt-argon2#10]
Fedora no longer allows code licensed under Creative Commons CC0 1.0 [1].  I see that the C source code is dual-licensed under "Creative Commons CC0 1.0 License/Waiver or the Apache Public License 2.0, at your option".  This is acceptable to Fedora.  I would like to ask if you could please add the same dual-license statement (or another license acceptable to Fedora [2]) in each of the perl files, LICENSE, and README that are distributed with this project.  This will allow Crypt::Argon2, which is needed by File::KDBX, which is needed by the next version of kpcli, to be added to Fedora.

Thanks.

[1] https://www.theregister.com/2022/07/25/fedora_sours_on_creative_commons/
[2] https://docs.fedoraproject.org/en-US/legal/allowed-licenses/

**Comment by Leont** [comment]
It's only CC0 because the reference implementation was CC0 when I started this module. To be honest I suspect it's probably easier to just change the license to Apache Public License 2.0 instead of dual-licensing.

**Comment by Leont** [comment]
I've just released 0.019 as APL2.0
