### ISSUE TITLE
Compiled shared object is not portable across kernel versions

### ISSUE THREAD

**Issue by oliwel** [Leont/crypt-argon2#11]
I use a docker container to create debian packages for several perl modules using the "dh-make-perl" wrapper. 

This worked fine the last years but we are now trying to migrate from buster to bookworm and see a very strange issue: The build host is my desktop running Ubuntu 22.04 with a 5.19 kernel. When I build the package inside the container it gets linked to "linux-vdso" which is obviously the one from the build host.

If I now install this package on a fresh bookworm system running with a "native" kernel 6.1 and run  `Crypt::Argon2::argon2id_pass`  I get a an `Illegal instruction` error and see this in the dmesg:

`perl[15562] trap invalid opcode ip:7f5e46e3567c sp:7ffc75428480 error:0 in Argon2.so[7f5e46e34000+6000]`

Building the package inside the container running on bookworm itself work.

**Comment by Leont** [comment]
Yeah, by default it compiles with native optimizations, but when packaging that may not be appropriate because target systems may lack instruction sets that the build system does have (e.g. AVX2/AVX512). Debian [patches this logic out](https://salsa.debian.org/perl-team/modules/packages/libcrypt-argon2-perl/-/commit/ccaa3ba6a852f3de314ad54c2da4618892026ef3), it sounds like you want to do the same.

**Comment by level420** [comment]
@Leont I've been also struggling when creating a docker image based on the official perl 5.38 debian bookworm image, where I've simply added `cpanm Crypt::Argon2`  to the Dockerfile. Then I've tested everything thoroughly on several development and staging servers, just to find out that it doesn't work on our production servers.

Would It be possible to have some env variable which could be set to disable the `-march-native` flag?

**Comment by level420** [comment]
Just found commit https://github.com/Leont/crypt-argon2/commit/356eaa4fceccf6a8fb15a4084ea662faba4ad6ce where this is already implemented via environment variable `CRYPT_ARGON2_ARCH`.

I think it would be helpful for others if this is documented and found via e.g. metacpan.org

**Comment by Leont** [comment]
> I think it would be helpful for others if this is documented and found via e.g. metacpan.org

That is a very reasonable point.

**Comment by Leont** [comment]
I have just release a trial version that implements runtime implementation switching. Testing (e.g. `cpanm LEONT/Crypt-Argon2-0.024-TRIAL.tar.gz`) in a wide variety of environments would be much appreciated.

**Comment by level420** [comment]
@Leont does this mean that when now installing via `cpanm LEONT/Crypt-Argon2-0.023-TRIAL.tar.gz` the default is not to set the `-arch` compiler flag?

**Comment by Leont** [comment]
> @Leont does this mean that when now installing via cpanm LEONT/Crypt-Argon2-0.023-TRIAL.tar.gz the default is not to set the -arch compiler flag?

It compiles versions with and without arch, and at runtime checks which ones are supported on that CPU :-)
