### ISSUE TITLE
Fedora packaging issue

### ISSUE THREAD

**Issue by hightowe** [Leont/crypt-argon2#12]
Hi Leon,

I am a little hesitant to file this as a bug report, but I bet that you would like to at least be aware: https://bugzilla.redhat.com/show_bug.cgi?id=2239146#c6

You may also be familiar enough with the CPU flags involved that you could add some valuable insight to that Fedora bug.

For some context, that bug spun out of this one, where there is a dependency on Crypt::Argon2: https://bugzilla.redhat.com/show_bug.cgi?id=2118421

Thanks for any help that you may be able to provide.

--
Lester

**Comment by Leont** [comment]
I suspect you may want to apply the same patch as Debian does: https://salsa.debian.org/perl-team/modules/packages/libcrypt-argon2-perl/-/commit/ccaa3ba6a852f3de314ad54c2da4618892026ef3

I really wish there was some environmental flag to detect if a dist is built for packaging or for local use, I don't have a good solution for that.

Or an automatic runtime switch between implementations.

**Comment by hightowe** [comment]
Thanks, Leon!

**Comment by vcunat** [comment]
I don't think stuff like `-march=native` is suitable for general defaults.  It's not just distros, but e.g. also containers.  For stuff that I see running, it only rarely happens that it was built on the same machine.

**Comment by nroach44** [comment]
I would agree with vcunat here - this is breaking a particular docker container (referenced above) and is exactly the kind of thing that has to be patched out in Buildroot.

Will `-march=native` work with a cross compiler? Does it provide any tangible benefit compared to leaving it out? Could you use `-mtune` instead?

**Comment by Leont** [comment]
> I don't think stuff like -march=native is suitable for general defaults. It's not just distros, but e.g. also containers. For stuff that I see running, it only rarely happens that it was built on the same machine.

I guess so. I wouldn't want to lose the optimization entirely though. Only enabling it when the `PERL5_CPAN_IS_RUNNING` environmental variable is true may be the right heuristic.

> Will -march=native work with a cross compiler?

Probably not.

> Does it provide any tangible benefit compared to leaving it out? Could you use -mtune instead?

There would be no benefit to using `-mtune`, the whole point is to use AVX2/AVX512 to speed up the code by a factor 2 (or more?).

**Comment by vcunat** [comment]
The normal way how this is done (since at least mmx) is that you compile multiple versions of relevant functions (those where it makes a big difference) and then choose the right one during runtime.

**Comment by Leont** [comment]
> The normal way how this is done (since at least mmx) is that you compile multiple versions of relevant functions (those where it makes a big difference) and then choose the right one during runtime.

I know, but I didn't write the code I just wrote a Perl wrapper for it. My assembly is not good enough to fix that issue. The original is [here](https://github.com/P-H-C/phc-winner-argon2/)

**Comment by Leont** [comment]
It seems libsodium has such an implementation, I should probably take a look at that

**Comment by vcunat** [comment]
Like this?  https://github.com/jedisct1/libsodium/commit/ad4584d45590654b9d863ced90d2b2561d5cfbda#commitcomment-129441988

**Comment by hightowe** [comment]
@Leont - I am not sure this is a good idea, and my example below is a Linux-only solution. but tossing it out anyway...

You could consider having the Perl distro compile >1 versions of the argon2 C library, each with gcc various optimization flags (-mtune=generic, -mavx, -mavx2) and then choose the best one that the CPU can handle at runtime, using CPU flags. On my desktop, these flags may be be the ones that I think you would care about:

```
$ cat /proc/cpuinfo |grep  -E '^flags\s+'|head -1|cut -d: -f2|xargs -n 1|grep avx
avx
avx2
avx_vnni
```
Again, not sure this is a good idea or if it is even feasible, but wanted to share it...

**Comment by jberger** [comment]
In a docker container, how would I prevent this optimization from being used? Indeed this is from https://github.com/convos-chat/convos/issues/862 as previously referenced

**Comment by Leont** [comment]
> In a docker container, how would I prevent this optimization from being used? Indeed this is from https://github.com/convos-chat/convos/issues/862 as previously referenced

Now that is a scenario I hadn't thought off. For I guess I need an extra flag to explicitly disable optimizations, I can't think of a way to automatically detect this. Another argument adding that runtime check.

**Comment by nroach44** [comment]
@Leont From the perspective of someone who has been involved in packaging stuff for other CPU families (see buildroot et al) it would be preferable that nothing in the upstream project assumes the host CPU matches the target CPU.

If you're building or packaging this yourself, perhaps adding an opt-in build flag would be best?

**Comment by jberger** [comment]
you know, now I'm even more confused. I execed into the container, pulled the tgz from metacpan, built and installed in the container, both with and without `-march=native` and convos still crashed both ways. It happens only during login, I can't think what else could do it, the timing on this bug is too perfect to not be it, and yet, maybe it isn't. I don't even know how to debug since it brings down the container.

Also, the tests pass in the container, so assuming there is good coverage, I would assume it would have triggered it. Very confusing

**Comment by nroach44** [comment]
@jberger If it's a segfault / invalid instruction it should show in the kernel logs (on the container host)

**Comment by jberger** [comment]
Ah, yes, there it is. And yes, I tried three times yesterday:

```
Apr  9 16:57:24 tuesdae kernel: [538388.513146] traps: perl[28145] trap invalid opcode ip:7ff4f0b29ea1 sp:7fffc72c85c0 error:0 in Argon2.so[7ff4f0b27000+6000]
Apr  9 17:06:50 tuesdae kernel: [538954.439675] traps: perl[1884927] trap invalid opcode ip:7efe0b2cdea1 sp:7fff3c7edc30 error:0 in Argon2.so[7efe0b2cb000+6000]
Apr  9 17:14:18 tuesdae kernel: [539402.012097] traps: perl[1895894] trap invalid opcode ip:7f458fcf7ea1 sp:7ffd6c62d4e0 error:0 in Argon2.so[7f458fcf5000+6000]
```

**Comment by jberger** [comment]
If I follow https://stackoverflow.com/a/2549593/468327 correctly, I think I'm hitting this line

```
    2ea1:	64 48 8b 04 25 28 00 	mov    %fs:0x28,%rax
```

Edit: more context:

```
0000000000002e90 <XS_Crypt__Argon2_argon2_pass>:
XS_Crypt__Argon2_argon2_pass():
    2e90:	41 57                	push   %r15
    2e92:	41 56                	push   %r14
    2e94:	41 55                	push   %r13
    2e96:	41 54                	push   %r12
    2e98:	55                   	push   %rbp
    2e99:	53                   	push   %rbx
    2e9a:	49 89 fc             	mov    %rdi,%r12
    2e9d:	48 83 ec 28          	sub    $0x28,%rsp
    2ea1:	64 48 8b 04 25 28 00 	mov    %fs:0x28,%rax
```

**Comment by jberger** [comment]
Looking at /proc/cpuinfo, I don't seem to have a `mov` instruction, though I have a `cmov`. Ok so this might be the issue, but I have no idea what to do from here. Thoughts?

**Comment by jberger** [comment]
Oh of course, I can't just rebuild and then try it in the container, the convos daemon is persistent and pid 1. So I need to run the container with a dummy entrypoint, rebuild the library, then start the daemon

**Comment by Leont** [comment]
> From the perspective of someone who has been involved in packaging stuff for other CPU families (see buildroot et al) it would be preferable that nothing in the upstream project assumes the host CPU matches the target CPU.

I don't like it, but if so many people tell me I'm wrong then I'm probably wrong.

The build system I have to deal with isn't very cooperative with what I need though. I'm going to have to puzzle on this one.

**Comment by jberger** [comment]
Ok, I have now proved it. I started the container with `sleep infinity` as its entrypoint, exec-ed in, fetched Crypt::Argon2 0.21, applied the patch as in https://salsa.debian.org/perl-team/modules/packages/libcrypt-argon2-perl/-/commit/ccaa3ba6a852f3de314ad54c2da4618892026ef3, built and installed, then ran the original entrypoint. It works fine, the application does not crash on login.

**Comment by jberger** [comment]
As mentioned on irc, here's a proposal:

In Build.PL add a new check for environment variable `CRYPT_ARGON2_ARCH`, if unset default to -march=native, same as now. Then make a magic value, say NONE or whatever that disables it. It would also allow people to set something else, I saw [somewhere](https://github.com/P-H-C/phc-winner-argon2/issues/308) that -march=core2 suggested as something that would be better than nothing but unlikely to break anyone. 
That would be like CRYPT_ARGON2_ARCH=core2

For future reference, more relevant links: 

* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828779
* https://github.com/P-H-C/phc-winner-argon2/issues/308

**Comment by Leont** [comment]
> From the perspective of someone who has been involved in packaging stuff for other CPU families (see buildroot et al) it would be preferable that nothing in the upstream project assumes the host CPU matches the target CPU.

I haven't forgotten about that, but fixing this involves shaving a lot of yaks first (mainly writing tooling that doesn't exist yet in this eco-system). Slowly moving towards that point though.

**Comment by Leont** [comment]
I have just release a trial version that implements runtime implementation switching. Testing (e.g. `cpanm LEONT/Crypt-Argon2-0.024-TRIAL.tar.gz`) in a wide variety of environments would be much appreciated.
