### ISSUE TITLE
argon2_needs_rehash documentation $salt_length and $output_length parameters are backwards

### ISSUE THREAD

**Issue by sbrownre** [Leont/crypt-argon2#13]
Hi,

While reading through the code for the `argon2_needs_rehash` function I noticed that the $salt_length and $output_length parameters are swapped in the documentation.

The parameter definition in the code I'm referring to is [Here](https://github.com/Leont/crypt-argon2/blob/6e55ebb4b5938e3801905961631bc376805eee3e/lib/Crypt/Argon2.pm#L27) and the swapped parameters in the documentation [Here](https://github.com/Leont/crypt-argon2/blob/6e55ebb4b5938e3801905961631bc376805eee3e/lib/Crypt/Argon2.pm#L135).

**Comment by Leont** [comment]
Thanks for the report, I've just updated the docs to correspond with reality.
