### ISSUE TITLE
add short description on pod documentation of script argon2-calibrate

### ISSUE THREAD

**Issue by joenio** [Leont/crypt-argon2#9]
Hello, I am packaging Crypt::Argon2 on Debian and I noted that is missing a short description on POD documentation of `script/argon2-calibrate`, the patch below was applied on Debian side adding the description.

```diff
--- a/script/argon2-calibrate
+++ b/script/argon2-calibrate
@@ -71,7 +71,7 @@
 
 =head1 NAME
 
-argon2-calibrate
+argon2-calibrate - script to find the appropriate argon2 parameters
 
 =head1 VERSION
 ```

That would be good to apply it here on upstream side as well, but I guess the patch above must be adapted before apply here on upstream cause I noted that the POD on metacpan (from where Debian fetch the code) is modified by dist-zilla somehow.

**Comment by Leont** [comment]
That is a good suggestion, I added that for the next version 🙂
